tmp

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,3 +2,33 @@
 . "$(dirname "$0")/_/husky.sh"
 
 npx lint-staged
+
+
+
+
+# STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "js$")
+# if [[ "$STAGED_FILES" = "" ]]; then
+#     exit 0
+# fi
+# PASS=true
+
+# for FILE in $STAGED_FILES
+# do
+# eslint –quiet "$FILE"
+
+# if [[ "$?" == 0 ]]; then
+#     echo "\t\033[32mESLint Passed: $FILE\033[0m"
+# else
+#     echo "\t\033[41mESLint Failed: $FILE\033[0m"
+#     PASS=false
+# fi
+
+
+
+# jest --bail --findRelatedTests $STAGED_FILES
+# if [[ "$?" == 0 ]]; then
+#     echo "\t\033[32mJest Tests Passed\033[0m"
+# else
+#     echo "\t\033[41mJest Tests Failed\033[0m"
+#     PASS=false
+# fi
